import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Card from "@/components/Card";
import UserCard from "@/components/UserCard";
import {timeframes} from '@/data/timeframes'
import { useState } from "react";

export default function Home() {
  const [category,setCategory] = useState('daily')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.userCardContainer}>
            <UserCard setCategory={setCategory} />
          </div>
          <div className={styles.cardsContainer}>
            {timeframes.map((item:any)=><Card data={item} category={category} key={item?.title} src={`/${item?.title}.svg`} colorClass={item?.title} />)}
          </div>
        </div>
      </main>
    </>
  );
}
